include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_classes_with_only_static_members: true
    eol_at_end_of_file: true
    noop_primitive_operations: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_lambdas: true
    use_colored_box: true
    use_decorated_box: true
    use_super_parameters: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

