name: wikigame
description: The Wikipedia game
version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_svg: ^0.14.0
  package_info: ^0.4.0+6
  shared_preferences: ^0.5.3+4
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.1
  firebase_crashlytics: ^0.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
