name: wikigame
description: WikiGame made with flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  go_router: ^10.0.0
  http: ^1.1.0
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  generate: true
